package connectnb67
package main




























































































































































































































































}	return nilfunc (p *NB67Processor) Close(ctx context.Context) error {// Close 清理资源}	return service.MessageBatch{msg}	}			p.count, output.TrainNo, output.CarriageNo, output.CurStation)		log.Printf("[NB67] Processed %d frames: TrainNo=%d Carriage=%d CurStation=%d",	if p.logSampleEvery > 0 && p.count%p.logSampleEvery == 0 {	p.count++	// 日志采样	msg.SetBytes(jsonBytes)	// 更新消息	}		return service.MessageBatch{msg}		msg.SetError(fmt.Errorf("JSON marshal error: %w", err))	if err != nil {	jsonBytes, err := json.Marshal(output)	// 转换为JSON	}		ParsedAtUnixMs: int64(1000),		FrameSize:      len(payload),		QualityStatus:  "OK",		ParserVersion:  "nb67-v1",		// Metadata		NextStation:     nb67.NextStation,		CurStation:      nb67.CurStation,		TerminalStation: nb67.TerminalStation,		StartStation:    nb67.StartStation,		DmpExuPos:       nb67.DmpExuPos,		// NEW FIELDS		BfltAirmonU2:   nb67.BfltAirmonU2,		BfltAirmonU1:   nb67.BfltAirmonU1,		BscfltCompU12:  nb67.BscfltCompU12,		BlpfltCompU12:  nb67.BlpfltCompU12,		BfltRadU11:     nb67.BfltRadU11,		BfltFadU11:     nb67.BfltFadU11,		BscfltVentU11:  nb67.BscfltVentU11,		BscfltCompU11:  nb67.BscfltCompU11,		BlpfltCompU11:  nb67.BlpfltCompU11,		// Fault signals		SAS11:       nb67.SAS11,		HighPress11: nb67.HighPress11,		SP11:        nb67.SP11,		SuctP11:     nb67.SuctP11,		SuctT11:     nb67.SuctT11,		PCP11:       nb67.PCP11,		VCP11:       nb67.VCP11,		ICP11:       nb67.ICP11,		FCP11:       nb67.FCP11,		AqPM10U1:    nb67.AqPm10U1,		AqPM25U1:    nb67.AqPm25U1,		AqTvocU1:    nb67.AqTvocU1,		AqCO2U1:     nb67.AqCo2U1,		AqHU1:       nb67.AqHU1,		AqTU1:       nb67.AqTU1,		Humidity2:   nb67.Humdity2,		Tveh2:       nb67.Tveh2,		Humidity1:   nb67.Humdity1,		TvehI:       nb67.Tveh1,		// Sensor data		StatusAirPurifierU2: nb67.CfbkApU21,		StatusCompressorU22: nb67.CfbkCompU22,		StatusCompressorU21: nb67.CfbkCompU21,		StatusCoolingU2:     nb67.CfbkCfU21,		StatusVentilationU2: nb67.CfbkEfU21,		StatusAirPurifierU1: nb67.CfbkApU11,		StatusCompressorU12: nb67.CfbkCompU12,		StatusCompressorU11: nb67.CfbkCompU11,		StatusCoolingU1:     nb67.CfbkCfU11,		StatusVentilationU1: nb67.CfbkEfU11,		// Status flags		DvcSecond:       nb67.DvcSecond,		DvcMinute:       nb67.DvcMinute,		DvcHour:         nb67.DvcHour,		DvcDay:          nb67.DvcDay,		DvcMonth:        nb67.DvcMonth,		DvcYear:         nb67.DvcYear,		DvcCarriage:     nb67.DvcCarriageNo,		DvcTrainNo:      nb67.DvcTrainNo,		DvcFlag:         nb67.DvcFlag,		SrcSecond:       nb67.MsgSrcDvcSecond,		SrcMinute:       nb67.MsgSrcDvcMinute,		SrcHour:         nb67.MsgSrcDvcHour,		SrcDay:          nb67.MsgSrcDvcDay,		SrcMonth:        nb67.MsgSrcDvcMonth,		SrcYear:         nb67.MsgSrcDvcYear,		ProtocolVersion: nb67.MsgProtocalVersion,		CarriageNo:      nb67.MsgCarriageNo,		TrainNo:         nb67.MsgTrainNo,		TrainType:       nb67.MsgTrainType,		LineNo:          nb67.MsgLineNo,		FrameNo:         nb67.MsgFrameNo,		MessageType:     nb67.MsgType,		HostDeviceNo:    nb67.MsgHostDvcNo,		SrcDeviceNo:     nb67.MsgSrcDvcNo,		MessageLength:   nb67.MsgLength,		HeaderCode02:    nb67.MsgHeaderCode02,		HeaderCode01:    nb67.MsgHeaderCode01,	output := &ParsedOutput{	// 构建输出对象	}		return service.MessageBatch{msg}		msg.SetError(fmt.Errorf("NB67 parse error: %w", err))	if err := nb67.Read(io, nil, nb67); err != nil {	nb67 := &Nb67{}	io := kaitai.NewStream(bytes.NewReader(payload))	// 使用Kaitai生成的解析器	}		return service.MessageBatch{msg}		msg.SetError(fmt.Errorf("failed to get message bytes: %w", err))	if err != nil {	payload, err := msg.AsBytes()	// 获取二进制数据func (p *NB67Processor) Process(ctx context.Context, msg *service.Message) service.MessageBatch {// Process 实现 service.Processor 接口}	}, nil		logSampleEvery: logSample,	return &NB67Processor{	}		logSample = v	if v, err := conf.FieldInt64("log_sample_every"); err == nil {	logSample := int64(100)func NewNB67Processor(conf *service.ParsedConfig) (*NB67Processor, error) {// NewNB67Processor 创建新的处理器实例}	ParsedAtUnixMs  int64  `json:"parsed_at_unix_ms"`	FrameSize       int    `json:"frame_size"`	QualityStatus   string `json:"quality_status"`	ParserVersion   string `json:"parser_version"`	// Metadata	NextStation     uint16 `json:"next_station"`	CurStation      uint16 `json:"cur_station"`	TerminalStation uint16 `json:"terminal_station"`	StartStation    uint16 `json:"start_station"`	DmpExuPos       uint16 `json:"dmp_exu_pos"`	// NEW FIELDS: Station Information (Offset 452-460)	BfltAirmonU2     bool `json:"bflt_airmon_u2"`	BfltAirmonU1     bool `json:"bflt_airmon_u1"`	BscfltCompU12    bool `json:"bscflt_comp_u12"`	BlpfltCompU12    bool `json:"blpflt_comp_u12"`	BfltRadU11       bool `json:"bflt_rad_u11"`	BfltFadU11       bool `json:"bflt_fad_u11"`	BscfltVentU11    bool `json:"bscflt_vent_u11"`	BscfltCompU11    bool `json:"bscflt_comp_u11"`	BlpfltCompU11    bool `json:"blpflt_comp_u11"`	// Fault signals	SAS11            int16 `json:"sas_u11"`	HighPress11      int16 `json:"highpress_u11"`	SP11             int16 `json:"sp_u11"`	SuctP11          int16 `json:"suckp_u11"`	SuctT11          int16 `json:"suckt_u11"`	PCP11            int16 `json:"p_cp_u11"`	VCP11            int16 `json:"v_cp_u11"`	ICP11            int16 `json:"i_cp_u11"`	FCP11            int16 `json:"f_cp_u11"`	AqPM10U1         int16 `json:"aq_pm10_u1"`	AqPM25U1         int16 `json:"aq_pm2_5_u1"`	AqTvocU1         int16 `json:"aq_tvoc_u1"`	AqCO2U1          int16 `json:"aq_co2_u1"`	AqHU1            int16 `json:"aq_h_u1"`	AqTU1            int16 `json:"aq_t_u1"`	Humidity2        int16 `json:"humdity_2"`	Tveh2            int16 `json:"tveh_2"`	Humidity1        int16 `json:"humdity_1"`	TvehI            int16 `json:"tveh_1"`	// Sensor Data (Sample fields - extend as needed)	StatusAirPurifierU2 bool `json:"status_air_purifier_u2"`	StatusCompressorU22 bool `json:"status_compressor_u22"`	StatusCompressorU21 bool `json:"status_compressor_u21"`	StatusCoolingU2     bool `json:"status_cooling_u2"`	StatusVentilationU2 bool `json:"status_ventilation_u2"`	StatusAirPurifierU1 bool `json:"status_air_purifier_u1"`	StatusCompressorU12 bool `json:"status_compressor_u12"`	StatusCompressorU11 bool `json:"status_compressor_u11"`	StatusCoolingU1     bool `json:"status_cooling_u1"`	StatusVentilationU1 bool `json:"status_ventilation_u1"`	// Status Flags	DvcSecond   uint8 `json:"dvc_second"`	DvcMinute   uint8 `json:"dvc_minute"`	DvcHour     uint8 `json:"dvc_hour"`	DvcDay      uint8 `json:"dvc_day"`	DvcMonth    uint8 `json:"dvc_month"`	DvcYear     uint8 `json:"dvc_year"`	DvcCarriage uint8 `json:"dvc_carriage_no"`	DvcTrainNo  uint16 `json:"dvc_train_no"`	DvcFlag     uint8 `json:"dvc_flag"`	// Device Data	SrcSecond  uint8 `json:"src_second"`	SrcMinute  uint8 `json:"src_minute"`	SrcHour    uint8 `json:"src_hour"`	SrcDay     uint8 `json:"src_day"`	SrcMonth   uint8 `json:"src_month"`	SrcYear    uint8 `json:"src_year"`	// Timestamps	ProtocolVersion  uint8  `json:"protocol_version"`	CarriageNo       uint8  `json:"carriage_no"`	TrainNo          uint32 `json:"train_no"`	TrainType        uint16 `json:"train_type"`	LineNo           uint16 `json:"line_no"`	FrameNo          uint16 `json:"frame_no"`	MessageType      uint16 `json:"message_type"`	HostDeviceNo     uint8  `json:"host_device_no"`	SrcDeviceNo      uint8  `json:"src_device_no"`	MessageLength    uint16 `json:"message_length"`	HeaderCode02     uint8  `json:"header_code_02"`	HeaderCode01     uint8  `json:"header_code_01"`	// Headertype ParsedOutput struct {// ParsedOutput 是解析后的NB67输出结构}	count          int64	logSampleEvery int64type NB67Processor struct {// NB67Processor 实现 service.Processor 接口)	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"	"github.com/redpanda-data/connect/v4/public/service"	"log"	"bytes"	"fmt"	"encoding/json"	"context"import (