// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type Nb67 struct {
	MsgHeaderCode01 uint8
	MsgHeaderCode02 uint8
	MsgLength uint16
	MsgSrcDvcNo uint8
	MsgHostDvcNo uint8
	MsgType uint16
	MsgFrameNo uint16
	MsgLineNo uint16
	MsgTrainType uint16
	MsgTrainNo uint32
	MsgCarriageNo uint8
	MsgProtocalVersion uint8
	MsgReversed1 uint16
	MsgReversed2 uint16
	MsgReversed3 uint16
	MsgReversed4 uint16
	MsgReversed5 uint16
	MsgSrcDvcYear uint8
	MsgSrcDvcMonth uint8
	MsgSrcDvcDay uint8
	MsgSrcDvcHour uint8
	MsgSrcDvcMinute uint8
	MsgSrcDvcSecond uint8
	DvcFlag uint8
	DvcTrainNo uint16
	DvcCarriageNo uint8
	DvcYear uint8
	DvcMonth uint8
	DvcDay uint8
	DvcHour uint8
	DvcMinute uint8
	DvcSecond uint8
	IgRsv0 uint8
	IgRsv1 uint8
	CfbkEfU11 bool
	IgRsv2 bool
	CfbkCfU11 bool
	IgRsv3 bool
	CfbkCompU11 bool
	CfbkCompU12 bool
	CfbkApU11 bool
	IgRsv4 bool
	CfbkEfU21 bool
	IgRsv5 bool
	CfbkCfU21 bool
	IgRsv6 bool
	CfbkCompU21 bool
	CfbkCompU22 bool
	CfbkApU21 bool
	IgRsv7 bool
	CfbkTppU1 bool
	CfbkTppU2 bool
	CfbkEvU1 bool
	CfbkEvU2 bool
	CfbkEwd bool
	CfbkExufan bool
	IgRsv9 bool
	IgRsv10 bool
	BocfltEfU11 bool
	BocfltEfU12 bool
	BocfltCfU11 bool
	BocfltCfU12 bool
	BfltVfdU11 bool
	BfltVfdComU11 bool
	BfltVfdU12 bool
	BfltVfdComU12 bool
	BlpfltCompU11 bool
	BscfltCompU11 bool
	BscfltVentU11 bool
	BlpfltCompU12 bool
	BscfltCompU12 bool
	BscfltVentU12 bool
	BfltFadU11 bool
	BfltFadU12 bool
	IgRsv11 bool
	IgRsv12 bool
	BfltRadU11 bool
	BfltRadU12 bool
	IgRsv13 bool
	IgRsv14 bool
	BfltApU11 bool
	IgRsv15 bool
	BfltExpboardU1 bool
	BfltFrstempU1 bool
	BfltRnttempU1 bool
	BfltSplytempU11 bool
	BfltSplytempU12 bool
	BfltCoiltempU11 bool
	BfltCoiltempU12 bool
	BfltInsptempU11 bool
	BfltInsptempU12 bool
	BfltLowpresU11 bool
	BfltLowpresU12 bool
	BfltHighpresU11 bool
	BfltHighpresU12 bool
	BfltDiffpresU1 bool
	BocfltEfU21 bool
	BocfltEfU22 bool
	BocfltCfU21 bool
	BocfltCfU22 bool
	BfltVfdU21 bool
	BfltVfdComU21 bool
	BfltVfdU22 bool
	BfltVfdComU22 bool
	BlpfltCompU21 bool
	BscfltCompU21 bool
	BscfltVentU21 bool
	BlpfltCompU22 bool
	BscfltCompU22 bool
	BscfltVentU22 bool
	BfltFadU21 bool
	BfltFadU22 bool
	IgRsv16 bool
	IgRsv17 bool
	BfltRadU21 bool
	BfltRadU22 bool
	IgRsv18 bool
	IgRsv19 bool
	BfltApU21 bool
	IgRsv20 bool
	BfltExpboardU2 bool
	BfltFrstempU2 bool
	BfltRnttempU2 bool
	BfltSplytempU21 bool
	BfltSplytempU22 bool
	BfltCoiltempU21 bool
	BfltCoiltempU22 bool
	BfltInsptempU21 bool
	BfltInsptempU22 bool
	BfltLowpresU21 bool
	BfltLowpresU22 bool
	BfltHighpresU21 bool
	BfltHighpresU22 bool
	BfltDiffpresU2 bool
	BfltEmergivt bool
	IgRsv240 bool
	IgRsv241 bool
	IgRsv242 bool
	BfltVehtempU1 bool
	IgRsv251 bool
	BfltVehtempU2 bool
	IgRsv252 bool
	BfltAirmonU1 bool
	BfltAirmonU2 bool
	BfltCurrentmon bool
	BfltTcms bool
	IgRsv26 uint8
	IgRsv27 uint8
	IgRsv28 uint8
	BfltTempover bool
	BfltPowersupplyU1 bool
	BfltPowersupplyU2 bool
	BfltExhaustfan bool
	BfltExhaustval bool
	IgRsv29 bool
	IgRsv30 bool
	IgRsv31 bool
	IgRsv32 int16
	IgRsv33 int16
	FasSys int16
	RasSys int16
	Tic int16
	Load int16
	Wrsv42 int16
	Tveh1 int16
	Humdity1 int16
	Tveh2 int16
	Humdity2 int16
	AqTU1 int16
	AqHU1 int16
	AqCo2U1 int16
	AqTvocU1 int16
	AqFormaldU1 int16
	AqPm25U1 int16
	AqPm10U1 int16
	AqRsvU1 int16
	WmodeU1 int16
	PresdiffU1 int16
	FasU1 int16
	RasU1 int16
	FadposU1 int16
	RadposU1 int16
	FCpU11 int16
	ICpU11 int16
	VCpU11 int16
	PCpU11 int16
	SucktU11 int16
	SuckpU11 int16
	SpU11 int16
	EevposU11 int16
	HighpressU11 int16
	SasU11 int16
	IcesU11 int16
	FCpU12 int16
	ICpU12 int16
	VCpU12 int16
	PCpU12 int16
	SucktU12 int16
	SuckpU12 int16
	SpU12 int16
	EevposU12 int16
	HighpressU12 int16
	SasU12 int16
	IcesU12 int16
	Wrsv124 int16
	AqTU2 int16
	AqHU2 int16
	AqCo2U2 int16
	AqTvocU2 int16
	AqFormaldU2 int16
	AqPm25U2 int16
	AqPm10U2 int16
	AqRsvU2 int16
	WmodeU2 int16
	PresdiffU2 int16
	FasU2 int16
	RasU2 int16
	FadposU2 int16
	RadposU2 int16
	FCpU21 int16
	ICpU21 int16
	VCpU21 int16
	PCpU21 int16
	SucktU21 int16
	SuckpU21 int16
	SpU21 int16
	EevposU21 int16
	HighpressU21 int16
	SasU21 int16
	IcesU21 int16
	FCpU22 int16
	ICpU22 int16
	VCpU22 int16
	PCpU22 int16
	SucktU22 int16
	SuckpU22 int16
	SpU22 int16
	EevposU22 int16
	HighpressU22 int16
	SasU22 int16
	IcesU22 int16
	IgRsv34 int16
	IgRsv35 int16
	IgRsv36 int16
	IgRsv37 int16
	IEfU11 int16
	IEfU12 int16
	ICfU11 int16
	ICfU12 int16
	IEfU21 int16
	IEfU22 int16
	ICfU21 int16
	ICfU22 int16
	IHvacU1 int16
	IHvacU2 int16
	IExufan int16
	IgRsv38 int16
	IgRsv39 int16
	Dwpower uint32
	DwemergOpTm uint32
	DwemergOpCnt uint32
	DwefOpTmU11 uint32
	IgRsv40 uint32
	DwcfOpTmU11 uint32
	IgRsv41 uint32
	DwcpOpTmU11 uint32
	DwcpOpTmU12 uint32
	IgRsv42 uint32
	IgRsv43 uint32
	DwfadOpCntU1 uint32
	DwradOpCntU1 uint32
	DwefOpCntU11 uint32
	IgRsv44 uint32
	DwcfOpCntU11 uint32
	IgRsv45 uint32
	DwcpOpCntU11 uint32
	DwcpOpCntU12 uint32
	IgRsv46 uint32
	IgRsv47 uint32
	DwefOpTmU21 uint32
	IgRsv48 uint32
	DwcfOpTmU21 uint32
	IgRsv49 uint32
	DwcpOpTmU21 uint32
	DwcpOpTmU22 uint32
	IgRsv50 uint32
	IgRsv51 uint32
	DwfadOpCntU2 uint32
	DwradOpCntU2 uint32
	DwefOpCntU21 uint32
	IgRsv52 uint32
	DwcfOpCntU21 uint32
	IgRsv53 uint32
	DwcpOpCntU21 uint32
	DwcpOpCntU22 uint32
	IgRsv54 uint32
	IgRsv55 uint32
	DwexufanOpTm uint32
	DwexufanOpCnt uint32
	DwdmpexuOpCnt uint32
	IgRsv56 uint32
	IgRsv57 uint32
	IgRsv58 uint32
	IgRsv59 uint32
	IgRsv60 uint32
	IgRsv61 uint32
	IgRsv62 uint32
	IgRsv63 uint32
	IgRsv64 uint32
	IgRsv65 uint32
	IgRsv66 uint32
	IgRsv67 uint32
	IgRsv68 uint32
	DmpExuPos uint16
	StartStation uint16
	TerminalStation uint16
	CurStation uint16
	NextStation uint16
	_io *kaitai.Stream
	_root *Nb67
	_parent kaitai.Struct
}
func NewNb67() *Nb67 {
	return &Nb67{
	}
}

func (this Nb67) IO_() *kaitai.Stream {
	return this._io
}

func (this *Nb67) Read(io *kaitai.Stream, parent kaitai.Struct, root *Nb67) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgHeaderCode01 = tmp1
	tmp2, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgHeaderCode02 = tmp2
	tmp3, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgLength = uint16(tmp3)
	tmp4, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgSrcDvcNo = tmp4
	tmp5, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgHostDvcNo = tmp5
	tmp6, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgType = uint16(tmp6)
	tmp7, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgFrameNo = uint16(tmp7)
	tmp8, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgLineNo = uint16(tmp8)
	tmp9, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgTrainType = uint16(tmp9)
	tmp10, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.MsgTrainNo = uint32(tmp10)
	tmp11, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgCarriageNo = tmp11
	tmp12, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgProtocalVersion = tmp12
	tmp13, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgReversed1 = uint16(tmp13)
	tmp14, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgReversed2 = uint16(tmp14)
	tmp15, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgReversed3 = uint16(tmp15)
	tmp16, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgReversed4 = uint16(tmp16)
	tmp17, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.MsgReversed5 = uint16(tmp17)
	tmp18, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgSrcDvcYear = tmp18
	tmp19, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgSrcDvcMonth = tmp19
	tmp20, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgSrcDvcDay = tmp20
	tmp21, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgSrcDvcHour = tmp21
	tmp22, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgSrcDvcMinute = tmp22
	tmp23, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MsgSrcDvcSecond = tmp23
	tmp24, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcFlag = tmp24
	tmp25, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.DvcTrainNo = uint16(tmp25)
	tmp26, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcCarriageNo = tmp26
	tmp27, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcYear = tmp27
	tmp28, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcMonth = tmp28
	tmp29, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcDay = tmp29
	tmp30, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcHour = tmp30
	tmp31, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcMinute = tmp31
	tmp32, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DvcSecond = tmp32
	tmp33, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IgRsv0 = tmp33
	tmp34, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IgRsv1 = tmp34
	tmp35, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkEfU11 = tmp35 != 0
	tmp36, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv2 = tmp36 != 0
	tmp37, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkCfU11 = tmp37 != 0
	tmp38, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv3 = tmp38 != 0
	tmp39, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkCompU11 = tmp39 != 0
	tmp40, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkCompU12 = tmp40 != 0
	tmp41, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkApU11 = tmp41 != 0
	tmp42, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv4 = tmp42 != 0
	tmp43, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkEfU21 = tmp43 != 0
	tmp44, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv5 = tmp44 != 0
	tmp45, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkCfU21 = tmp45 != 0
	tmp46, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv6 = tmp46 != 0
	tmp47, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkCompU21 = tmp47 != 0
	tmp48, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkCompU22 = tmp48 != 0
	tmp49, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkApU21 = tmp49 != 0
	tmp50, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv7 = tmp50 != 0
	tmp51, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkTppU1 = tmp51 != 0
	tmp52, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkTppU2 = tmp52 != 0
	tmp53, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkEvU1 = tmp53 != 0
	tmp54, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkEvU2 = tmp54 != 0
	tmp55, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkEwd = tmp55 != 0
	tmp56, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.CfbkExufan = tmp56 != 0
	tmp57, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv9 = tmp57 != 0
	tmp58, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv10 = tmp58 != 0
	tmp59, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltEfU11 = tmp59 != 0
	tmp60, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltEfU12 = tmp60 != 0
	tmp61, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltCfU11 = tmp61 != 0
	tmp62, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltCfU12 = tmp62 != 0
	tmp63, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdU11 = tmp63 != 0
	tmp64, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdComU11 = tmp64 != 0
	tmp65, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdU12 = tmp65 != 0
	tmp66, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdComU12 = tmp66 != 0
	tmp67, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BlpfltCompU11 = tmp67 != 0
	tmp68, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltCompU11 = tmp68 != 0
	tmp69, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltVentU11 = tmp69 != 0
	tmp70, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BlpfltCompU12 = tmp70 != 0
	tmp71, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltCompU12 = tmp71 != 0
	tmp72, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltVentU12 = tmp72 != 0
	tmp73, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltFadU11 = tmp73 != 0
	tmp74, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltFadU12 = tmp74 != 0
	tmp75, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv11 = tmp75 != 0
	tmp76, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv12 = tmp76 != 0
	tmp77, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltRadU11 = tmp77 != 0
	tmp78, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltRadU12 = tmp78 != 0
	tmp79, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv13 = tmp79 != 0
	tmp80, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv14 = tmp80 != 0
	tmp81, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltApU11 = tmp81 != 0
	tmp82, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv15 = tmp82 != 0
	tmp83, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltExpboardU1 = tmp83 != 0
	tmp84, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltFrstempU1 = tmp84 != 0
	tmp85, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltRnttempU1 = tmp85 != 0
	tmp86, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltSplytempU11 = tmp86 != 0
	tmp87, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltSplytempU12 = tmp87 != 0
	tmp88, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltCoiltempU11 = tmp88 != 0
	tmp89, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltCoiltempU12 = tmp89 != 0
	tmp90, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltInsptempU11 = tmp90 != 0
	tmp91, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltInsptempU12 = tmp91 != 0
	tmp92, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltLowpresU11 = tmp92 != 0
	tmp93, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltLowpresU12 = tmp93 != 0
	tmp94, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltHighpresU11 = tmp94 != 0
	tmp95, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltHighpresU12 = tmp95 != 0
	tmp96, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltDiffpresU1 = tmp96 != 0
	tmp97, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltEfU21 = tmp97 != 0
	tmp98, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltEfU22 = tmp98 != 0
	tmp99, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltCfU21 = tmp99 != 0
	tmp100, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BocfltCfU22 = tmp100 != 0
	tmp101, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdU21 = tmp101 != 0
	tmp102, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdComU21 = tmp102 != 0
	tmp103, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdU22 = tmp103 != 0
	tmp104, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVfdComU22 = tmp104 != 0
	tmp105, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BlpfltCompU21 = tmp105 != 0
	tmp106, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltCompU21 = tmp106 != 0
	tmp107, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltVentU21 = tmp107 != 0
	tmp108, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BlpfltCompU22 = tmp108 != 0
	tmp109, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltCompU22 = tmp109 != 0
	tmp110, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BscfltVentU22 = tmp110 != 0
	tmp111, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltFadU21 = tmp111 != 0
	tmp112, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltFadU22 = tmp112 != 0
	tmp113, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv16 = tmp113 != 0
	tmp114, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv17 = tmp114 != 0
	tmp115, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltRadU21 = tmp115 != 0
	tmp116, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltRadU22 = tmp116 != 0
	tmp117, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv18 = tmp117 != 0
	tmp118, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv19 = tmp118 != 0
	tmp119, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltApU21 = tmp119 != 0
	tmp120, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv20 = tmp120 != 0
	tmp121, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltExpboardU2 = tmp121 != 0
	tmp122, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltFrstempU2 = tmp122 != 0
	tmp123, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltRnttempU2 = tmp123 != 0
	tmp124, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltSplytempU21 = tmp124 != 0
	tmp125, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltSplytempU22 = tmp125 != 0
	tmp126, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltCoiltempU21 = tmp126 != 0
	tmp127, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltCoiltempU22 = tmp127 != 0
	tmp128, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltInsptempU21 = tmp128 != 0
	tmp129, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltInsptempU22 = tmp129 != 0
	tmp130, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltLowpresU21 = tmp130 != 0
	tmp131, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltLowpresU22 = tmp131 != 0
	tmp132, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltHighpresU21 = tmp132 != 0
	tmp133, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltHighpresU22 = tmp133 != 0
	tmp134, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltDiffpresU2 = tmp134 != 0
	tmp135, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltEmergivt = tmp135 != 0
	tmp136, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv240 = tmp136 != 0
	tmp137, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv241 = tmp137 != 0
	tmp138, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv242 = tmp138 != 0
	tmp139, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVehtempU1 = tmp139 != 0
	tmp140, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv251 = tmp140 != 0
	tmp141, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltVehtempU2 = tmp141 != 0
	tmp142, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv252 = tmp142 != 0
	tmp143, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltAirmonU1 = tmp143 != 0
	tmp144, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltAirmonU2 = tmp144 != 0
	tmp145, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltCurrentmon = tmp145 != 0
	tmp146, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltTcms = tmp146 != 0
	this._io.AlignToByte()
	tmp147, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IgRsv26 = tmp147
	tmp148, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IgRsv27 = tmp148
	tmp149, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IgRsv28 = tmp149
	tmp150, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltTempover = tmp150 != 0
	tmp151, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltPowersupplyU1 = tmp151 != 0
	tmp152, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltPowersupplyU2 = tmp152 != 0
	tmp153, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltExhaustfan = tmp153 != 0
	tmp154, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.BfltExhaustval = tmp154 != 0
	tmp155, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv29 = tmp155 != 0
	tmp156, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv30 = tmp156 != 0
	tmp157, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.IgRsv31 = tmp157 != 0
	this._io.AlignToByte()
	tmp158, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv32 = int16(tmp158)
	tmp159, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv33 = int16(tmp159)
	tmp160, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FasSys = int16(tmp160)
	tmp161, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.RasSys = int16(tmp161)
	tmp162, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Tic = int16(tmp162)
	tmp163, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Load = int16(tmp163)
	tmp164, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Wrsv42 = int16(tmp164)
	tmp165, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Tveh1 = int16(tmp165)
	tmp166, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Humdity1 = int16(tmp166)
	tmp167, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Tveh2 = int16(tmp167)
	tmp168, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Humdity2 = int16(tmp168)
	tmp169, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqTU1 = int16(tmp169)
	tmp170, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqHU1 = int16(tmp170)
	tmp171, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqCo2U1 = int16(tmp171)
	tmp172, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqTvocU1 = int16(tmp172)
	tmp173, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqFormaldU1 = int16(tmp173)
	tmp174, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqPm25U1 = int16(tmp174)
	tmp175, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqPm10U1 = int16(tmp175)
	tmp176, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqRsvU1 = int16(tmp176)
	tmp177, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.WmodeU1 = int16(tmp177)
	tmp178, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.PresdiffU1 = int16(tmp178)
	tmp179, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FasU1 = int16(tmp179)
	tmp180, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.RasU1 = int16(tmp180)
	tmp181, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FadposU1 = int16(tmp181)
	tmp182, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.RadposU1 = int16(tmp182)
	tmp183, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FCpU11 = int16(tmp183)
	tmp184, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICpU11 = int16(tmp184)
	tmp185, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.VCpU11 = int16(tmp185)
	tmp186, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.PCpU11 = int16(tmp186)
	tmp187, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SucktU11 = int16(tmp187)
	tmp188, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SuckpU11 = int16(tmp188)
	tmp189, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SpU11 = int16(tmp189)
	tmp190, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.EevposU11 = int16(tmp190)
	tmp191, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.HighpressU11 = int16(tmp191)
	tmp192, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SasU11 = int16(tmp192)
	tmp193, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IcesU11 = int16(tmp193)
	tmp194, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FCpU12 = int16(tmp194)
	tmp195, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICpU12 = int16(tmp195)
	tmp196, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.VCpU12 = int16(tmp196)
	tmp197, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.PCpU12 = int16(tmp197)
	tmp198, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SucktU12 = int16(tmp198)
	tmp199, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SuckpU12 = int16(tmp199)
	tmp200, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SpU12 = int16(tmp200)
	tmp201, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.EevposU12 = int16(tmp201)
	tmp202, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.HighpressU12 = int16(tmp202)
	tmp203, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SasU12 = int16(tmp203)
	tmp204, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IcesU12 = int16(tmp204)
	tmp205, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.Wrsv124 = int16(tmp205)
	tmp206, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqTU2 = int16(tmp206)
	tmp207, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqHU2 = int16(tmp207)
	tmp208, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqCo2U2 = int16(tmp208)
	tmp209, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqTvocU2 = int16(tmp209)
	tmp210, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqFormaldU2 = int16(tmp210)
	tmp211, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqPm25U2 = int16(tmp211)
	tmp212, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqPm10U2 = int16(tmp212)
	tmp213, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.AqRsvU2 = int16(tmp213)
	tmp214, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.WmodeU2 = int16(tmp214)
	tmp215, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.PresdiffU2 = int16(tmp215)
	tmp216, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FasU2 = int16(tmp216)
	tmp217, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.RasU2 = int16(tmp217)
	tmp218, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FadposU2 = int16(tmp218)
	tmp219, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.RadposU2 = int16(tmp219)
	tmp220, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FCpU21 = int16(tmp220)
	tmp221, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICpU21 = int16(tmp221)
	tmp222, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.VCpU21 = int16(tmp222)
	tmp223, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.PCpU21 = int16(tmp223)
	tmp224, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SucktU21 = int16(tmp224)
	tmp225, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SuckpU21 = int16(tmp225)
	tmp226, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SpU21 = int16(tmp226)
	tmp227, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.EevposU21 = int16(tmp227)
	tmp228, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.HighpressU21 = int16(tmp228)
	tmp229, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SasU21 = int16(tmp229)
	tmp230, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IcesU21 = int16(tmp230)
	tmp231, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.FCpU22 = int16(tmp231)
	tmp232, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICpU22 = int16(tmp232)
	tmp233, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.VCpU22 = int16(tmp233)
	tmp234, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.PCpU22 = int16(tmp234)
	tmp235, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SucktU22 = int16(tmp235)
	tmp236, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SuckpU22 = int16(tmp236)
	tmp237, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SpU22 = int16(tmp237)
	tmp238, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.EevposU22 = int16(tmp238)
	tmp239, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.HighpressU22 = int16(tmp239)
	tmp240, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.SasU22 = int16(tmp240)
	tmp241, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IcesU22 = int16(tmp241)
	tmp242, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv34 = int16(tmp242)
	tmp243, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv35 = int16(tmp243)
	tmp244, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv36 = int16(tmp244)
	tmp245, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv37 = int16(tmp245)
	tmp246, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IEfU11 = int16(tmp246)
	tmp247, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IEfU12 = int16(tmp247)
	tmp248, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICfU11 = int16(tmp248)
	tmp249, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICfU12 = int16(tmp249)
	tmp250, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IEfU21 = int16(tmp250)
	tmp251, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IEfU22 = int16(tmp251)
	tmp252, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICfU21 = int16(tmp252)
	tmp253, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.ICfU22 = int16(tmp253)
	tmp254, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IHvacU1 = int16(tmp254)
	tmp255, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IHvacU2 = int16(tmp255)
	tmp256, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IExufan = int16(tmp256)
	tmp257, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv38 = int16(tmp257)
	tmp258, err := this._io.ReadS2be()
	if err != nil {
		return err
	}
	this.IgRsv39 = int16(tmp258)
	tmp259, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Dwpower = uint32(tmp259)
	tmp260, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwemergOpTm = uint32(tmp260)
	tmp261, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwemergOpCnt = uint32(tmp261)
	tmp262, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwefOpTmU11 = uint32(tmp262)
	tmp263, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv40 = uint32(tmp263)
	tmp264, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcfOpTmU11 = uint32(tmp264)
	tmp265, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv41 = uint32(tmp265)
	tmp266, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpTmU11 = uint32(tmp266)
	tmp267, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpTmU12 = uint32(tmp267)
	tmp268, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv42 = uint32(tmp268)
	tmp269, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv43 = uint32(tmp269)
	tmp270, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwfadOpCntU1 = uint32(tmp270)
	tmp271, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwradOpCntU1 = uint32(tmp271)
	tmp272, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwefOpCntU11 = uint32(tmp272)
	tmp273, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv44 = uint32(tmp273)
	tmp274, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcfOpCntU11 = uint32(tmp274)
	tmp275, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv45 = uint32(tmp275)
	tmp276, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpCntU11 = uint32(tmp276)
	tmp277, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpCntU12 = uint32(tmp277)
	tmp278, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv46 = uint32(tmp278)
	tmp279, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv47 = uint32(tmp279)
	tmp280, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwefOpTmU21 = uint32(tmp280)
	tmp281, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv48 = uint32(tmp281)
	tmp282, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcfOpTmU21 = uint32(tmp282)
	tmp283, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv49 = uint32(tmp283)
	tmp284, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpTmU21 = uint32(tmp284)
	tmp285, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpTmU22 = uint32(tmp285)
	tmp286, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv50 = uint32(tmp286)
	tmp287, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv51 = uint32(tmp287)
	tmp288, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwfadOpCntU2 = uint32(tmp288)
	tmp289, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwradOpCntU2 = uint32(tmp289)
	tmp290, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwefOpCntU21 = uint32(tmp290)
	tmp291, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv52 = uint32(tmp291)
	tmp292, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcfOpCntU21 = uint32(tmp292)
	tmp293, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv53 = uint32(tmp293)
	tmp294, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpCntU21 = uint32(tmp294)
	tmp295, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwcpOpCntU22 = uint32(tmp295)
	tmp296, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv54 = uint32(tmp296)
	tmp297, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv55 = uint32(tmp297)
	tmp298, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwexufanOpTm = uint32(tmp298)
	tmp299, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwexufanOpCnt = uint32(tmp299)
	tmp300, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DwdmpexuOpCnt = uint32(tmp300)
	tmp301, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv56 = uint32(tmp301)
	tmp302, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv57 = uint32(tmp302)
	tmp303, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv58 = uint32(tmp303)
	tmp304, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv59 = uint32(tmp304)
	tmp305, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv60 = uint32(tmp305)
	tmp306, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv61 = uint32(tmp306)
	tmp307, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv62 = uint32(tmp307)
	tmp308, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv63 = uint32(tmp308)
	tmp309, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv64 = uint32(tmp309)
	tmp310, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv65 = uint32(tmp310)
	tmp311, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv66 = uint32(tmp311)
	tmp312, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv67 = uint32(tmp312)
	tmp313, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IgRsv68 = uint32(tmp313)
	tmp314, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.DmpExuPos = uint16(tmp314)
	tmp315, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.StartStation = uint16(tmp315)
	tmp316, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.TerminalStation = uint16(tmp316)
	tmp317, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.CurStation = uint16(tmp317)
	tmp318, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.NextStation = uint16(tmp318)
	return err
}
